import type { Metadata } from "next";
import { Geist, Geist_Mono, Playfair_Display } from "next/font/google";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import "@ant-design/v5-patch-for-react-19";
import "antd/dist/reset.css";
import "./globals.css";
import AntdStyleWrapper from "@/components/AntdStyleWrapper";
import { ToastProvider } from "@/context/ToastContext";
import { App } from "antd";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair", // ✅ define your own variable here
});
export const metadata: Metadata = {
  title: "Raj Milan",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${playfair.variable} antialiased`}
      >
        <AntdStyleWrapper>
          <AntdRegistry>
            <ToastProvider>
              <App>{children}</App>
            </ToastProvider>
          </AntdRegistry>
        </AntdStyleWrapper>
      </body>
    </html>
  );
}
